; generated by SuperSlicer 2.4 on 2023-10-06 at 19:52:21 UTC

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.46mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.46mm
; top infill extrusion width = 0.44mm
; first layer extrusion width = 0.60mm

; object:{"name":"First_Layer_Test","id":"First_Layer_Test.stl id:0 copy 0","object_center":[117.500000,117.000000,0.000000],"boundingbox_center":[117.500000,117.000000,0.100000],"boundingbox_size":[75.000000,75.000000,0.200000]}
; plater:{"center":[117.500000,117.000000,0.000000],"boundingbox_center":[117.500000,117.000000,0.100000],"boundingbox_size":[75.000000,75.000000,0.200000]}

;TYPE:Custom
Start Print


; Pre-Processed for Cancel-Object support by preprocess_cancellation v0.2.0
; 1 known objects
EXCLUDE_OBJECT_DEFINE NAME=First_Layer_Test_stl_id_0_copy_0 CENTER=117.511,117.068 POLYGON=[[80.304,79.803],[80.304,154.198],[154.698,154.198],[154.698,79.803]]
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

BED_MESH_CALIBRATE
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
;_TOOLCHANGE 0
M104 S200 ; set temperature
M109 S200 ; set temperature and wait for it to be reached
M190 S50 ; set bed temperature and wait for it to be reached
M107
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
TIMELAPSE_TAKE_FRAME
G1 Z0.3 F7800
G1 E-0.4 F240
G1 X86.084 Y86.107 F7800
G1 E0 F240
;TYPE:Skirt
;WIDTH:0.44
G1 F1800
G1 X75.362 Y96.826 E0.71029
G1 X73.836 Y99.22 E0.84329
G1 X73.439 Y101.468 E0.95023
G1 X73.439 Y132.52 E2.405
G1 X74.052 Y135.29 E2.53792
G1 X75.36 Y137.161 E2.64486
G1 X97.333 Y159.139 E4.10085
G1 X99.727 Y160.664 E4.23382
G1 X101.975 Y161.061 E4.34076
G1 X133.026 Y161.063 E5.79548
G1 X135.796 Y160.45 E5.92844
G1 X137.667 Y159.141 E6.03538
G1 X159.639 Y137.172 E7.49103
G1 X161.164 Y134.779 E7.62399
G1 X161.561 Y132.531 E7.73094
G1 X161.563 Y101.484 E9.18547
G1 X160.95 Y98.714 E9.31839
G1 X159.642 Y96.844 E9.42533
G1 X137.667 Y74.861 E10.88155
G1 X135.273 Y73.335 E11.01456
G1 X133.025 Y72.938 E11.1215
G1 X101.975 Y72.938 E12.57617
G1 X99.205 Y73.551 E12.70909
G1 X97.335 Y74.859 E12.81603
G1 X86.126 Y86.065 E13.55855
G1 X86.392 Y86.33 F7800
G1 F1800
G1 X75.627 Y97.092 E14.27165
G1 X74.211 Y99.288 E14.39407
G1 X73.814 Y101.468 E14.49788
G1 X73.814 Y132.52 E15.95265
G1 X74.365 Y135.073 E16.075
G1 X75.626 Y136.895 E16.17881
G1 X97.599 Y158.873 E17.63479
G1 X99.795 Y160.289 E17.75719
G1 X101.975 Y160.686 E17.861
G1 X133.026 Y160.688 E19.31572
G1 X135.579 Y160.137 E19.4381
G1 X137.401 Y158.876 E19.54191
G1 X159.373 Y136.907 E20.99757
G1 X160.789 Y134.711 E21.11995
G1 X161.186 Y132.531 E21.22376
G1 X161.188 Y101.484 E22.67829
G1 X160.637 Y98.932 E22.80064
G1 X159.376 Y97.109 E22.90445
G1 X137.401 Y75.126 E24.36067
G1 X135.205 Y73.71 E24.4831
G1 X133.025 Y73.313 E24.58691
G1 X101.975 Y73.313 E26.04158
G1 X99.422 Y73.864 E26.16392
G1 X97.6 Y75.125 E26.26774
G1 X86.434 Y86.288 E27.00744
G92 E0
G1 E-0.4 F240
; printing object First_Layer_Test.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=First_Layer_Test_stl_id_0_copy_0
G1 X80.304 Y101.593 F7800
G1 E0 F240
;TYPE:External perimeter
;WIDTH:0.604
G1 F1800
G1 X102.1 Y79.803 E2.07432
G1 X132.9 Y79.803 E4.14728
G1 X154.698 Y101.609 E6.22247
G1 X154.696 Y132.406 E8.29523
G1 X132.901 Y154.198 E10.3696
G1 X102.1 Y154.196 E12.44262
G1 X80.304 Y132.395 E14.51747
G1 X80.304 Y101.653 E16.58653
;WIPE_START
G1 X80.704 Y101.593 F7800
;WIPE_END
G92 E0
G1 E-0.4 F240
G1 X132.489 Y79.965 F7800
G1 E0 F240
;TYPE:Solid infill
;WIDTH:0.603568
G1 F1800
G1 X154.304 Y101.78 E2.0749
G1 X154.304 Y102.543 E2.12622
G1 X131.958 Y80.197 E4.25164
G1 X131.195 Y80.197 E4.30296
G1 X154.304 Y103.306 E6.50096
G1 X154.304 Y104.069 E6.55228
G1 X130.432 Y80.197 E8.82285
G1 X129.669 Y80.197 E8.87418
G1 X154.304 Y104.832 E11.21733
G1 X154.304 Y105.595 E11.26866
G1 X128.906 Y80.197 E13.68439
G1 X128.143 Y80.197 E13.73572
G1 X154.304 Y106.358 E16.22403
G1 X154.304 Y107.121 E16.27536
G1 X127.379 Y80.197 E18.83625
G1 X126.616 Y80.197 E18.88758
G1 X154.304 Y107.884 E21.52106
G1 X154.304 Y108.647 E21.57238
G1 X125.853 Y80.197 E24.27844
G1 X125.09 Y80.197 E24.32976
G1 X154.304 Y109.41 E27.1084
G1 X154.304 Y110.174 E27.15972
G1 X124.327 Y80.197 E30.01095
G1 X123.564 Y80.197 E30.06227
G1 X154.303 Y110.937 E32.98607
G1 X154.303 Y111.7 E33.03739
G1 X122.801 Y80.197 E36.03378
G1 X122.037 Y80.197 E36.0851
G1 X154.303 Y112.463 E39.15406
G1 X154.303 Y113.226 E39.20539
G1 X121.274 Y80.197 E42.34693
G1 X120.511 Y80.197 E42.39826
G1 X154.303 Y113.989 E45.61238
G1 X154.303 Y114.752 E45.6637
G1 X119.748 Y80.197 E48.95041
G1 X118.985 Y80.197 E49.00173
G1 X154.303 Y115.515 E52.36102
G1 X154.303 Y116.278 E52.41234
G1 X118.222 Y80.197 E55.84421
G1 X117.459 Y80.197 E55.89553
G1 X154.303 Y117.041 E59.39998
G1 X154.303 Y117.804 E59.4513
G1 X116.696 Y80.197 E63.02833
G1 X115.932 Y80.197 E63.07966
G1 X154.303 Y118.568 E66.72927
G1 X154.303 Y119.331 E66.78059
G1 X115.169 Y80.197 E70.50278
G1 X114.406 Y80.197 E70.5541
G1 X154.303 Y120.094 E74.34887
G1 X154.303 Y120.857 E74.4002
G1 X113.643 Y80.197 E78.26755
G1 X112.88 Y80.197 E78.31887
G1 X154.303 Y121.62 E82.25881
G1 X154.303 Y122.383 E82.31013
G1 X112.117 Y80.197 E86.32264
G1 X111.354 Y80.197 E86.37397
G1 X154.303 Y123.146 E90.45906
G1 X154.303 Y123.909 E90.51038
G1 X110.59 Y80.197 E94.66806
G1 X109.827 Y80.197 E94.71938
G1 X154.303 Y124.672 E98.94964
G1 X154.303 Y125.435 E99.00096
G1 X109.064 Y80.197 E103.3038
G1 X108.301 Y80.197 E103.35512
G1 X154.303 Y126.198 E107.73054
G1 X154.302 Y126.961 E107.78186
G1 X107.538 Y80.197 E112.22986
G1 X106.775 Y80.197 E112.28119
G1 X154.302 Y127.725 E116.80176
G1 X154.302 Y128.488 E116.85309
G1 X106.012 Y80.197 E121.44625
G1 X105.248 Y80.197 E121.49757
G1 X154.302 Y129.251 E126.16331
G1 X154.302 Y130.014 E126.21463
G1 X104.485 Y80.197 E130.95295
G1 X103.722 Y80.197 E131.00428
G1 X154.302 Y130.777 E135.81518
G1 X154.302 Y131.54 E135.8665
G1 X102.959 Y80.197 E140.74999
G1 X102.263 Y80.197 E140.79679
G1 X102.23 Y80.231 E140.79999
G1 X154.272 Y132.273 E145.74998
G1 X153.89 Y132.654 E145.78627
G1 X101.848 Y80.612 E150.73626
G1 X101.466 Y80.994 E150.77256
G1 X153.509 Y133.036 E155.72255
G1 X153.127 Y133.418 E155.75884
G1 X101.085 Y81.375 E160.70884
G1 X100.703 Y81.757 E160.74514
G1 X152.746 Y133.799 E165.69514
G1 X152.364 Y134.181 E165.73143
G1 X100.321 Y82.138 E170.68143
G1 X99.94 Y82.52 E170.71773
G1 X151.982 Y134.562 E175.66773
G1 X151.601 Y134.944 E175.70402
G1 X99.558 Y82.901 E180.65403
G1 X99.177 Y83.283 E180.69032
G1 X151.219 Y135.325 E185.64034
G1 X150.838 Y135.707 E185.67663
G1 X98.795 Y83.664 E190.62664
G1 X98.413 Y84.046 E190.66293
G1 X150.456 Y136.088 E195.61295
G1 X150.074 Y136.47 E195.64924
G1 X98.032 Y84.427 E200.59926
G1 X97.65 Y84.809 E200.63555
G1 X149.693 Y136.851 E205.58557
G1 X149.311 Y137.233 E205.62187
G1 X97.268 Y85.19 E210.57189
G1 X96.887 Y85.572 E210.60818
G1 X148.93 Y137.614 E215.55821
G1 X148.548 Y137.996 E215.5945
G1 X96.505 Y85.953 E220.54453
G1 X96.124 Y86.335 E220.58082
G1 X148.166 Y138.378 E225.53085
G1 X147.785 Y138.759 E225.56714
G1 X95.742 Y86.716 E230.51718
G1 X95.36 Y87.098 E230.55347
G1 X147.403 Y139.141 E235.50351
G1 X147.022 Y139.522 E235.5398
G1 X94.979 Y87.479 E240.48984
G1 X94.597 Y87.861 E240.52613
G1 X146.64 Y139.904 E245.47617
G1 X146.258 Y140.285 E245.51246
G1 X94.216 Y88.242 E250.46251
G1 X93.834 Y88.624 E250.4988
G1 X145.877 Y140.667 E255.44884
G1 X145.495 Y141.048 E255.48514
G1 X93.452 Y89.005 E260.43518
G1 X93.071 Y89.387 E260.47148
G1 X145.114 Y141.43 E265.42153
G1 X144.732 Y141.811 E265.45782
G1 X92.689 Y89.768 E270.40787
G1 X92.307 Y90.15 E270.44417
G1 X144.35 Y142.193 E275.39422
G1 X143.969 Y142.575 E275.43051
G1 X91.926 Y90.531 E280.38057
G1 X91.544 Y90.913 E280.41686
G1 X143.587 Y142.956 E285.36693
G1 X143.206 Y143.338 E285.40322
G1 X91.163 Y91.295 E290.35328
G1 X90.781 Y91.676 E290.38957
G1 X142.824 Y143.719 E295.33964
G1 X142.442 Y144.101 E295.37593
G1 X90.399 Y92.058 E300.326
G1 X90.018 Y92.439 E300.36229
G1 X142.061 Y144.482 E305.31236
G1 X141.679 Y144.864 E305.34866
G1 X89.636 Y92.821 E310.29873
G1 X89.254 Y93.202 E310.33502
G1 X141.298 Y145.245 E315.2851
G1 X140.916 Y145.627 E315.32139
G1 X88.873 Y93.584 E320.27147
G1 X88.491 Y93.965 E320.30776
G1 X140.535 Y146.008 E325.25784
G1 X140.153 Y146.39 E325.29413
G1 X88.11 Y94.347 E330.24421
G1 X87.728 Y94.728 E330.28051
G1 X139.771 Y146.772 E335.23059
G1 X139.39 Y147.153 E335.26688
G1 X87.346 Y95.11 E340.21697
G1 X86.965 Y95.491 E340.25327
G1 X139.008 Y147.535 E345.20336
G1 X138.627 Y147.916 E345.23965
G1 X86.583 Y95.873 E350.18974
G1 X86.201 Y96.254 E350.22603
G1 X138.245 Y148.298 E355.17613
G1 X137.863 Y148.679 E355.21242
G1 X85.82 Y96.636 E360.16252
G1 X85.438 Y97.017 E360.19881
G1 X137.482 Y149.061 E365.14891
G1 X137.1 Y149.442 E365.1852
G1 X85.057 Y97.399 E370.13531
G1 X84.675 Y97.78 E370.1716
G1 X136.719 Y149.824 E375.1217
G1 X136.337 Y150.205 E375.158
G1 X84.293 Y98.162 E380.1081
G1 X83.912 Y98.543 E380.1444
G1 X135.955 Y150.587 E385.09451
G1 X135.574 Y150.968 E385.1308
G1 X83.53 Y98.925 E390.08091
G1 X83.149 Y99.306 E390.1172
G1 X135.192 Y151.35 E395.06732
G1 X134.811 Y151.732 E395.10361
G1 X82.767 Y99.688 E400.05373
G1 X82.385 Y100.069 E400.09002
G1 X134.429 Y152.113 E405.04014
G1 X134.047 Y152.495 E405.07643
G1 X82.004 Y100.451 E410.02656
G1 X81.622 Y100.832 E410.06285
G1 X133.666 Y152.876 E415.01297
G1 X133.284 Y153.258 E415.04927
G1 X81.24 Y101.214 E419.99939
G1 X80.859 Y101.595 E420.03569
G1 X132.903 Y153.639 E424.98582
G1 X132.738 Y153.804 E425.00149
G1 X132.304 Y153.804 E425.03065
G1 X80.698 Y102.198 E429.93917
G1 X80.698 Y102.961 E429.9905
G1 X131.541 Y153.804 E434.82643
G1 X130.778 Y153.804 E434.87776
G1 X80.698 Y103.724 E439.6411
G1 X80.698 Y104.487 E439.69243
G1 X130.015 Y153.804 E444.38318
G1 X129.252 Y153.804 E444.43451
G1 X80.698 Y105.25 E449.05267
G1 X80.698 Y106.013 E449.104
G1 X128.488 Y153.804 E453.64957
G1 X127.725 Y153.804 E453.7009
G1 X80.698 Y106.776 E458.17388
G1 X80.698 Y107.54 E458.2252
G1 X126.962 Y153.804 E462.62559
G1 X126.199 Y153.804 E462.67692
G1 X80.698 Y108.303 E467.00472
G1 X80.698 Y109.066 E467.05605
G1 X125.436 Y153.804 E471.31126
G1 X124.672 Y153.804 E471.36259
G1 X80.698 Y109.829 E475.54521
G1 X80.698 Y110.592 E475.59654
G1 X123.909 Y153.804 E479.70657
G1 X123.146 Y153.803 E479.7579
G1 X80.698 Y111.355 E483.79534
G1 X80.698 Y112.118 E483.84666
G1 X122.383 Y153.803 E487.81151
G1 X121.62 Y153.803 E487.86284
G1 X80.698 Y112.882 E491.7551
G1 X80.698 Y113.645 E491.80643
G1 X120.856 Y153.803 E495.6261
G1 X120.093 Y153.803 E495.67743
G1 X80.698 Y114.408 E499.42451
G1 X80.698 Y115.171 E499.47583
G1 X119.33 Y153.803 E503.15032
G1 X118.567 Y153.803 E503.20165
G1 X80.698 Y115.934 E506.80355
G1 X80.698 Y116.697 E506.85488
G1 X117.804 Y153.803 E510.38419
G1 X117.041 Y153.803 E510.43552
G1 X80.698 Y117.46 E513.89224
G1 X80.698 Y118.224 E513.94356
G1 X116.277 Y153.803 E517.32769
G1 X115.514 Y153.803 E517.37902
G1 X80.698 Y118.987 E520.69056
G1 X80.698 Y119.75 E520.74189
G1 X114.751 Y153.803 E523.98083
G1 X113.988 Y153.803 E524.03216
G1 X80.698 Y120.513 E527.19852
G1 X80.698 Y121.276 E527.24985
G1 X113.225 Y153.803 E530.34362
G1 X112.461 Y153.803 E530.39495
G1 X80.698 Y122.039 E533.41612
G1 X80.698 Y122.802 E533.46745
G1 X111.698 Y153.803 E536.41604
G1 X110.935 Y153.803 E536.46737
G1 X80.698 Y123.565 E539.34337
G1 X80.698 Y124.329 E539.39469
G1 X110.172 Y153.803 E542.1981
G1 X109.409 Y153.803 E542.24943
G1 X80.698 Y125.092 E544.98025
G1 X80.698 Y125.855 E545.03157
G1 X108.646 Y153.803 E547.6898
G1 X107.882 Y153.802 E547.74113
G1 X80.698 Y126.618 E550.32677
G1 X80.698 Y127.381 E550.37809
G1 X107.119 Y153.802 E552.89114
G1 X106.356 Y153.802 E552.94247
G1 X80.698 Y128.144 E555.38293
G1 X80.698 Y128.907 E555.43425
G1 X105.593 Y153.802 E557.80212
G1 X104.83 Y153.802 E557.85345
G1 X80.698 Y129.671 E560.14873
G1 X80.698 Y130.434 E560.20005
G1 X104.066 Y153.802 E562.42274
G1 X103.303 Y153.802 E562.47407
G1 X80.698 Y131.197 E564.62417
G1 X80.698 Y131.96 E564.67549
G1 X102.772 Y154.034 E566.77507
G92 E0
G1 E-0.4 F240
; stop printing object First_Layer_Test.stl id:0 copy 0
EXCLUDE_OBJECT_END NAME=First_Layer_Test_stl_id_0_copy_0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
UPDATE_DELAYED_GCODE ID=POWER_OFF_PRINTER_CHECK DURATION=30
; filament used [mm] = 610.37
; filament used [cm3] = 1.47
; total filament used [g] = 0.00
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 5m 59s

; SuperSlicer_config = begin
; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = D:\\Downloads\\Biqu_B1_print_bedmodel.stl
; bed_custom_texture = D:\\Downloads\\Biqu_B1_print_bed_textures\\Biqu B1 print bed texture_grid.png
; bed_shape = 0x0,235x0,235x234,0x234
; bed_temperature = 50
; before_layer_gcode = TIMELAPSE_TAKE_FRAME
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 100%
; bridge_internal_acceleration = 0
; bridge_internal_fan_speed = -1
; bridge_overlap = 90%
; bridge_overlap_min = 80%
; bridge_speed = 60%
; bridge_speed_internal = 150%
; bridge_type = nozzle
; bridged_infill_margin = 200%
; brim_acceleration = 0
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_separation = 0
; brim_speed = 50%
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; default_speed = 100
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\nUPDATE_DELAYED_GCODE ID=POWER_OFF_PRINTER_CHECK DURATION=30\n
; enforce_full_fill_volume = 1
; enforce_retract_first_layer = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_acceleration = 0
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 100%
; external_perimeter_extrusion_width = 
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 105%
; extrusion_width = 
; fan_always_on = 1
; fan_below_layer_time = 60
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 0
; filament_custom_variables = ""
; filament_density = 0
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 0
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = biquB1
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 18%
; fill_pattern = adaptivecubic
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 50
; first_layer_extrusion_spacing = 140%
; first_layer_extrusion_width = 
; first_layer_flow_ratio = 100%
; first_layer_height = 75%
; first_layer_infill_speed = 0
; first_layer_min_speed = 0
; first_layer_size_compensation = 0
; first_layer_size_compensation_layers = 1
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 200%
; fuzzy_skin_thickness = 150%
; gap_fill_acceleration = 0
; gap_fill_enabled = 1
; gap_fill_flow_match_perimeter = 0%
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 50%
; gcode_comments = 0
; gcode_filename_illegal_char = [<>:"/\\\\|?*]
; gcode_flavor = klipper
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; gcode_resolution = 0
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 100%
; infill_extrusion_width = 
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 300%
; init_z_rotate = 0
; interface_shells = 0
; ironing = 0
; ironing_acceleration = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 50%
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 75%
; max_print_height = 250
; max_print_speed = 80
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 35
; min_layer_height = 5%
; min_length = 0.035
; min_print_speed = 10
; min_skirt_length = 0
; min_width_top_surface = 100%
; mmu_segmented_region_max_width = 0
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_acceleration = 0
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 105%
; perimeter_extrusion_width = 
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 60%
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = biquB1
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = biquB1
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.1
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0.4
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 4
; seam_angle_cost = 80%
; seam_gap = 15%
; seam_position = aligned
; seam_travel_cost = 20%
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 6
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 110%
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 50%
; solid_fill_pattern = rectilineargapfill
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 105%
; solid_infill_extrusion_width = 
; solid_infill_overlap = 100%
; solid_infill_speed = 30%
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = Start Print\nG28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n\nBED_MESH_CALIBRATE
; start_gcode_manual = 0
; support_material = 0
; support_material_acceleration = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0.2
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_contact_distance_type = filament
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 100%
; support_material_interface_acceleration = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_fan_speed = -1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 50%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60%
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_perimeters = 80%
; thin_perimeters_all = 20%
; thin_walls = 1
; thin_walls_acceleration = 0
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 100%
; threads = 8
; thumbnails = 0x0,0x0
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_format = PNG
; thumbnails_with_bed = 1
; time_cost = 0
; time_estimation_compensation = 100%
; time_start_gcode = 20
; time_toolchange = 30
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 100%
; top_infill_extrusion_width = 
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 50%
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 1500
; travel_deceleration_use_target = 1
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_inside_depth = 50%
; wipe_inside_end = 1
; wipe_inside_start = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
; SuperSlicer_config = end
